app = "phoxtra-cloud"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
_APP_ENV = "production"
_APP_DOMAIN = "cloud.phoxtra.com"
_APP_DOMAIN_TARGET = "cloud.phoxtra.com"
_APP_DOMAIN_TARGET_CNAME = "cloud.phoxtra.com"
_APP_CONSOLE_HOSTNAMES = "cloud.phoxtra.com,phoxtra-cloud.fly.dev"
_APP_OPTIONS_FORCE_HTTPS = "disabled"
_APP_OPTIONS_ROUTER_PROTECTION = "disabled"
_APP_STORAGE_LIMIT = "1073741824"
_APP_CONSOLE_WHITELIST_ROOT = "disabled"
_APP_SYSTEM_EMAIL_NAME = "Phoxtra Cloud"
_APP_SYSTEM_EMAIL_ADDRESS = "phoxmanglobal@gmail.com"
_APP_DB_ADAPTER = "mariadb"
_APP_DB_HOST = "phoxtra-db.internal"
_APP_DB_PORT = "3306"
_APP_DB_USER = "appwrite"
_APP_DB_SCHEMA = "appwrite"
_APP_CONNECTIONS_MAX = "1024"
_APP_POOL_CLIENTS = "1"
_APP_REDIS_HOST = "127.0.0.1"
_APP_REDIS_PORT = "6379"
_APP_REDIS_USER = ""
_APP_REDIS_PASS = ""
_APP_REDIS_AUTH = ""
_APP_EXECUTOR_HOST = "http://127.0.0.1:8082/v1"
_APP_EXECUTOR_SECRET = "your-secret-key"
_APP_FUNCTIONS_RUNTIMES = "node-16.0,node-18.0,node-20.0,python-3.9,python-3.10,python-3.11,php-8.0,php-8.1,php-8.2,deno-1.40,dart-3.0,bun-1.0"
_APP_FUNCTIONS_BUILD_TIMEOUT = "900"
_APP_EXECUTOR_LOCAL = "true"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "phoxtra_data"
  destination = "/var/lib/phoxtra"
